apiVersion: v1
kind: ConfigMap
metadata:
 name: metricbeat-modules
 namespace: kube-system
 labels:
 k8s-app: metricbeat
data:
 system.yml: |-
 - module: system
 period: 10s
 metricsets:
 - cpu
 - load
 - memory
 - network
 - process
 - process_summary
 processes: ['.*']
 process.include_top_n:
 by_cpu: 5 # include top 5 processes by CPU
 by_memory: 5 # include top 5 processes by memory
 kubernetes.yml: |-
 - module: kubernetes
 metricsets:
 - node
 - system
 - pod
 - container
 - volume
 enabled: true
 period: 10s
 hosts: ["192.168.99.100:8443"]
